# Generated by Django 3.0.4 on 2020-03-31 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.TextField(max_length=500)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('sender', models.CharField(blank=True, default='help@loansimple.in', max_length=1000, null=True)),
                ('to', models.CharField(max_length=1000)),
                ('cc', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('reply_to', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('clicked', 'Clicked'), ('opened', 'Opened')], max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='core.Email')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ('-created_at',),
            },
        ),
    ]
