# Generated by Django 3.0.4 on 2020-04-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(blank=True, default='abhishek@loansimple.in', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emailevent',
            name='type',
            field=models.CharField(choices=[('opened', 'Opened'), ('clicked', 'Clicked')], max_length=20),
        ),
    ]
